[package]
name = "thallium"
version = "0.4.0"
edition = "2021"
description = "A basic game engine"
exclude = ["crates/"]
license = "MIT"
repository = "https://github.com/HomelikeBrick42/ThalliumECS"

[workspace]
members = ["crates/*"]

[dependencies]
thallium_ecs = { path = "crates/thallium_ecs" }
