[package]
name = "thallium_ecs"
version = "0.3.0"
edition = "2021"
description = "A basic ECS"
license = "MIT"
repository = "https://github.com/HomelikeBrick42/ThalliumECS"

[dependencies]
hashbrown = "0.14.3"
parking_lot = "0.12.1"
rayon = "1.9.0"
