[package]
name = "thallium"
version = "0.4.2"
edition = "2021"
description = "A basic game engine"
exclude = ["crates/"]
license = "MIT"
repository = "https://github.com/HomelikeBrick42/Thallium"

[workspace]
members = ["crates/*"]

[dependencies]
thallium_ecs = { path = "crates/thallium_ecs", version = "0.4.1" }
thallium_derive = { path = "crates/thallium_derive", version = "0.1.0" }

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints]
workspace = true
