[package]
name = "thallium_ecs"
version = "0.1.5"
edition = "2021"
description = "A basic ECS"
license-file = "LICENCE"
repository = "https://github.com/HomelikeBrick42/ThalliumECS"

[dependencies]
hashbrown = "0.14.3"
parking_lot = "0.12.1"
rayon = "1.9.0"
slotmap = "1.0.7"
