[package]
name = "thallium_derive"
version = "0.1.0"
edition = "2021"
description = "The derive macros for the thallium crate"
license = "MIT"
repository = "https://github.com/HomelikeBrick42/Thallium"

[dependencies]

[lints]
workspace = true
