[package]
name = "thallium_ecs"
version = "0.5.0"
edition = "2021"
description = "The ECS for the thallium crate"
license = "MIT"
repository = "https://github.com/HomelikeBrick42/Thallium"

[dependencies]
parking_lot = "0.12.1"
rayon = "1.9.0"

[lints]
workspace = true
